### PR TITLE
Des 356

### PR DESCRIPTION
**Pull request by wyseguyonline**
Initial PR for avatar-display.

### CODE REVIEW

**Comment by wyseguyonline** [comment]
@aaronkaka @JasonLantz @StommePoes

**Comment by JasonLantz** [comment]
looks good....

**Comment by StommePoes** [comment]
The border: 0 is a little redundant. Were you seeing a border?

Just a thought...
Is it a good idea to have an image be clickable? Should it go somewhere, or do something? Would it not be better to have examples of the avatar image with an anchor and/or a button wrapping it and using the avatar class, remove any default/browser styles for these elements?

It's not inaccessible as it is now, however a user may at most hear that the "avatar image" is a clickable, which tells them less than something with a link or button role.

The consumer should then have to decide if their avatars need to be clickable, and if so, whether it should then Go Somewhere or Do Something and choose the correct version.

Lastly perhaps if an image should be clickable it should get a visual-feedback or cursor:pointer?

**Comment by wyseguyonline** [comment]
I can strip out the click/enter handlers.  My thinking is that in a number of situations we need the avatar to be clickable (e.g. on the user profile page in Console and most likely on the app-header).  However, if the consumer of the component should just wrap it in a button, then that would be preferable to keep the scope of this component to a minimum.  A user should be hearing more than just "avatar image" if the consumer of the component has configured it to say more.

The border: 0px is only redundant when we're including Elements.  If Elements is not present, then we still need that style defined.  I do not believe our components should always assume that Elements is present.

**Comment by StommePoes** [comment]
Should the consumer wrap anchors or buttons and then deal with styles, or should those be options within the avatar itself? (could be scope-creep, or could be a way to ensure consumers don't mess things up too much :P )

**Comment by wyseguyonline** [comment]
I think some reasonable styling should be done by the component (e.g. border: 0).  If the consumer wants a border, let them specify one.  If the consumer wants behaviors added to the avatar, let them specify them.

**Comment by StommePoes** [comment]
Oh I wasn't commenting about the border:0 anymore. I meant something else.

**Comment by umahaea** [comment]
Closing an reopening this PR. Squashing all commits to single commit.

**Pull request closed without merging**
